# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               zdsh
tagline:             ''
description:         ''
url:                 "zdsh.github.io"
paginate:            5

# About/contact
author:
  name:              zdsh
  url:               zhaodongshang.com
  email:             zhaodongshang@gmail.com

gems:
   - jekyll-paginate
   - jekyll-gist

markdown: kramdown
#permalink: /blog/:year/:month/:day/:title

